
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
  labels:
    app: postgresql
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS test (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL
    );
